CountryStateCityTK/Controllers/AuthController.cs
using BAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using UI.ViewModels.UserInfoViewModels;

namespace UI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserInfoRepo _userInfoRepo;
        public AuthController(IUserInfoRepo userInfoRepo)
        {
            _userInfoRepo = userInfoRepo;
        }
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserInfoViewModel vm)
        {
            var user = await _userInfoRepo.GetUserInfo(vm.UserName, vm.Password);
            HttpContext.Session.SetInt32("User", user.UserId);
            HttpContext.Session.SetString("UserName", user.UserName);
            return RedirectToAction("GetAll", "Country");
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserInfoViewModel vm)
        {
            if (vm == null)
            {
                return NotFound();
            }
            else
            {
                var userInfo = new UserInfo
                {
                    UserName = vm.UserName,
                    Password = vm.Password
                };
                await _userInfoRepo.RegisterUser(userInfo);
                return RedirectToAction("Login");

            }
        }
    }
}

CountryStateCityTK/Controllers/CityController.cs
using BAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UI.ViewModels;

namespace UI.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityRepo cityRepo;
        private readonly IStateRepo stateRepo;
        public CityController(ICityRepo cityRepo, IStateRepo stateRepo)
        {
            this.cityRepo = cityRepo;
            this.stateRepo = stateRepo;
        }
        public async Task<IActionResult> Index()
        {
            var city = await this.cityRepo.GetAll();
            return View(city);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var state = await this.stateRepo.GetAll();
            ViewBag.Statelist = new SelectList(state, "Id", "Name");
            return View();
        }
        public async Task<IActionResult> Create(CityViewModel vm)
        {
            var city = new City
            {
                Name = vm.Name,
                StateId = vm.StateId
            };
            await this.cityRepo.Save(city);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Edit(int Id)
        {
            var city = await this.cityRepo.GetById(Id);
            var states = await this.stateRepo.GetAll();
            ViewBag.Statelist = new SelectList(states, "Id", "Name");
            var vm = new CityViewModel
            {
                Id = city.Id,
                Name = city.Name,
                StateId = city.StateId
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(CityViewModel vm)
        {
            var city = new City
            {
                Id = (int)vm.Id,
                Name = vm.Name,
                StateId = vm.StateId
            };
            await this.cityRepo.Edit(city);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var city = await this.cityRepo.GetById(Id);
            await this.cityRepo.RemoveData(city);
            return RedirectToAction("Index");
        }
    }
}

CountryStateCityTK/Controllers/SkillController.cs
using BAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using UI.ViewModels;
using UI.ViewModels.SkillViewModels;

namespace UI.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillRepo _skillRepo;

        public SkillController(ISkillRepo skillRepo)
        {
            _skillRepo = skillRepo;
        }
        
        public async Task<IActionResult> GetAll(string sortOrder, string filterText, int pageNumber = 1, int pageSize = 3, string searchText = null)
        {
            List<SkillViewModel> vm = new List<SkillViewModel>();

            ViewData["SortFilter"] = sortOrder;
            ViewData["sortId"] = sortOrder == "Id_desc" ? "" : "Id_desc";
            ViewData["sortTitle"] = sortOrder == "title_desc" ? "title_asc" : "title_desc";

            var skills = await this._skillRepo.GetAll();
            if(searchText != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchText = filterText;
            }
            ViewData["filterData"] = searchText;

            switch (sortOrder)
            {
                case "Id_desc": skills = skills.OrderByDescending(x=>x.Id).ToList(); break; 
                case "title_desc": skills = skills.OrderByDescending(x=>x.Title).ToList(); break; 
                case "title_asc": skills = skills.OrderBy(x=>x.Title).ToList(); break;
                default: skills = skills.OrderBy(x=>x.Id).ToList(); break; 
            }

            var totalCount = 0;
            if(!string.IsNullOrEmpty(searchText))
            {
                skills = skills.Where(x=>x.Title.Contains(searchText));
            }
            totalCount = skills.Count();
            skills = skills.Skip((pageNumber-1)*pageSize).Take(pageSize).ToList();
            foreach (var skill in skills)
            {
                vm.Add(new SkillViewModel { Id = skill.Id, Title = skill.Title });
            }
            var pvm = new PagedSkillViewModel
            {
                Skills = vm,
                PageInfo = new Utility.PageInfo
                {
                    PageNumber = pageNumber,
                    PageSize = pageSize,
                    TotalItems = totalCount
                }
            };
            return View(pvm);
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int Id)
        {
            SkillViewModel vm = new SkillViewModel();
            var skill = await _skillRepo.GetById(Id);
            vm.Id = skill.Id;
            vm.Title = skill.Title;
            return View(vm);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateSkillViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var skill = new Skill
                {
                    Title = vm.Title
                };
                await _skillRepo.Save(skill);
                return RedirectToAction("GetAll");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            SkillViewModel vm = new SkillViewModel();
            var country = await _skillRepo.GetById(Id);
            vm.Id = country.Id;
            vm.Title = country.Title;
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SkillViewModel vm)
        {
            var skill = new Skill
            {
                Id = (int)vm.Id,
                Title = vm.Title
            };
            await this._skillRepo.Edit(skill);
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var city = await _skillRepo.GetById(Id);
            await _skillRepo.RemoveData(city);
            return RedirectToAction("GetAll");
        }
    }
}

CountryStateCityTK/Controllers/StateController.cs
using BAL;
using DAL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using UI.ViewModels;

namespace UI.Controllers
{
    public class StateController : Controller
    {
        private readonly IStateRepo stateRepo;
        private readonly ICountryRepo countryRepo;
        public StateController(ICountryRepo countryRepo, IStateRepo stateRepo)
        {
            this.countryRepo = countryRepo;
            this.stateRepo = stateRepo;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var states = await this.stateRepo.GetAll();
            return View(states);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var countries = await this.countryRepo.GetAll();
            ViewBag.Countrylist = new SelectList(countries, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(StateViewModel vm)
        {
            var state = new State
            {
                Name = vm.Name,
                CountryId = vm.CountryId
            };
            await this.stateRepo.Save(state);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var state = await this.stateRepo.GetById(Id);
            var vm = new StateViewModel
            {
                Id = state.Id,
                Name = state.Name,
                CountryId = state.CountryId
            };
            var countries = await this.countryRepo.GetAll();
            ViewBag.Countrylist = new SelectList(countries, "Id", "Name");
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(StateViewModel vm)
        {
            var state = new State
            {   
                Id = (int)vm.Id,
                Name = vm.Name,
                CountryId = vm.CountryId
            };
            await this.stateRepo.Edit(state);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            var state = await this.stateRepo.GetById(Id);
            await this.stateRepo.RemoveData(state);
            return RedirectToAction("Index");
        }
    }
}

CountryStateCityTK/Views/Shared/_ActionLinks.cshtml
@model int
<td>
    @Html.ActionLink("Edit", "Edit", new { Id = Model }) |
    @Html.ActionLink("Delete", "Delete", new { Id = Model })
</td>

CountryStateCityTK/Views/Shared/_HeaderNav.cshtml
@inject IHttpContextAccessor ContextAccessor 

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CountryStateCityTK</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="GetAll">Country</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="Index">State</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="GetAll">Skill</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                </li>
            </ul>
            @if(ContextAccessor.HttpContext.Session.GetInt32("User") != null)
            {
                @(ContextAccessor.HttpContext.Session.GetString("UserName") + " ")
                <a asp-action="Logout" asp-controller="Auth">Logout</a>
            }
        </div>
    </div>
</nav>

CountryStateCityTK/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CountryStateCityTK</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CountryStateCityTK.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_HeaderNav"/>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CountryStateCityTK - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>